# Railway deployment configuration for Sudoku Solver Backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
