# Railway deployment configuration for Sudoku Solver Backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && source venv/bin/activate && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
